version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mogiapp-mysql-dev
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    # Limit memory to 1GB for MySQL (sufficient for development)
    mem_limit: 1024m
    mem_reservation: 512m

  # Backend server service with hot-reloading
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.unified
      target: development
    container_name: mogiapp-server-dev
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules
    # Limit memory to 1GB for Node.js server
    mem_limit: 1024m
    mem_reservation: 512m

  # Frontend service with hot-reloading
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.unified
      target: development
    container_name: mogiapp-frontend-dev
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server
    # Remove volume mounts to avoid conflicts
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # Limit memory to 1GB for frontend development
    mem_limit: 1024m
    mem_reservation: 512m
    # Add platform specification to fix rollup issue
    platform: linux/amd64

# Define named volumes
volumes:
  mysql_data_dev: