version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mogiapp-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # Limit memory to 1GB for MySQL
    mem_limit: 1024m
    mem_reservation: 512m

  # Backend server service
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.unified
      target: production
    container_name: mogiapp-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server/uploads:/app/uploads
    # Limit memory to 1GB for Node.js server
    mem_limit: 1024m
    mem_reservation: 512m

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.unified
      target: production
    container_name: mogiapp-frontend
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    # Limit memory to 1GB for frontend
    mem_limit: 1024m
    mem_reservation: 512m

# Define named volumes
volumes:
  mysql_data: