version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: mogiapp-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # Backend server service
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: mogiapp-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mogiapp?authSource=admin
      - PORT=5000
      - JWT_SECRET=mogiapp-secret-key-docker
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mogiapp-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules

# Define named volumes
volumes:
  mongodb_data: