version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mogiapp-mysql-dev
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"

  # Backend server service with hot-reloading
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.unified
      target: development
    container_name: mogiapp-server-dev
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend service with hot-reloading
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.unified
      target: development
    container_name: mogiapp-frontend-dev
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules

# Define named volumes
volumes:
  mysql_data_dev: