version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mogiapp-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mogiapp
      MYSQL_USER: mogiuser
      MYSQL_PASSWORD: mogipassword

  # Backend server service
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: mogiapp-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://mogiuser:mogipassword@mysql:3306/mogiapp
      - PORT=5000
      - JWT_SECRET=mogiapp-secret-key-docker
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mogiapp-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules

# Define named volumes
volumes:
  mysql_data: