version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mogiapp-mysql-prod
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend server service
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: mogiapp-server-prod
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mogiapp-frontend-prod
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - server

# Define named volumes
volumes:
  mysql_data: